name: Auto Deploy

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Push from SIFR-AI
      run: |
        git config user.name "sifr-ai"
        git config user.email "deploy@sifr-ai.com"
        git pull origin main --rebase
        git add .
        git commit -m "Autonomous push from SIFR-AI" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/hmralawadhi/sifr-ai-homepage.git main
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Trigger Cloudflare Pages Deploy
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/${{ secrets.CLOUDFLARE_PROJECT_NAME }}/deployments" \
        -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
        -H "Content-Type: application/json" \
        --data '{}'
