name: Autonomous SIFR-AI Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Auto-detect build folder
        id: detect
        run: |
          if [ -d "dist" ]; then
            echo "FOLDER=dist" >> $GITHUB_ENV
          elif [ -d "build" ]; then
            echo "FOLDER=build" >> $GITHUB_ENV
          else
            echo "❌ No dist or build folder found."
            exit 1
          fi

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy $FOLDER --project-name=<YOUR_CF_PROJECT_NAME>
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
