#!/bin/bash
set -e

# Repo details
REPO="hmralawadhi/sifr-ai-homepage"
BRANCH="main"
TOKEN="${SIFR_AI_TOKEN}"  # Stored securely inside SIFR-AI
TMP_DIR=$(mktemp -d)

# Clone repo
git clone --depth 1 --branch $BRANCH https://x-access-token:${TOKEN}@github.com/$REPO.git $TMP_DIR
cd $TMP_DIR

# Replace site files with the new generated ones from SIFR-AI
cp -R /path/to/sifr-ai/generated/files/* .

# Commit & push
git config --global user.name "SIFR-AI Bot"
git config --global user.email "bot@sifr-ai.com"
git add .
git commit -m "Autonomous update $(date)" || echo "No changes to commit"
git push origin $BRANCH
