name: Auto Deploy to Cloudflare Pages
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Configure Git
      run: |
        git config --global user.name "sifr-ai"
        git config --global user.email "deploy@sifr-ai.com"

    - name: Commit & Push Changes
      run: |
        git add .
        git commit -m "Autonomous push from SIFR-AI" || echo "No changes to commit"
        git push origin main
