name: Auto Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.email "sifr-ai-bot@users.noreply.github.com"
          git config --global user.name "SIFR-AI Bot"

      - name: Make changes (placeholder)
        run: |
          echo "Auto update from SIFR-AI at $(date)" > last_update.txt

      - name: Commit changes
        run: |
          git add .
          git commit -m "Auto deploy from SIFR-AI" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/hmralawadhi/sifr-ai-homepage.git
          git push origin main

      - name: Trigger Cloudflare Pages Deployment
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          PROJECT_NAME: sifr-ai
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${PROJECT_NAME}/deployments" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json"
