name: Auto Deploy from SIFR-AI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # we'll use our own token for pushing

    - name: Configure Git and Push Changes
      run: |
        git config --global user.name "sifr-ai"
        git config --global user.email "deploy@sifr-ai.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/hmralawadhi/sifr-ai-homepage.git
        git add .
        git commit -m "Autonomous push from SIFR-AI" || echo "No changes to commit"
        git push origin main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
