name: Auto Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Push from SIFR-AI
      run: |
        git config user.name "sifr-ai"
        git config user.email "deploy@sifr-ai.com"
        git add .
        git commit -m "Autonomous push from SIFR-AI"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
