name: SIFR-AI Autonomous Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Commit and push updated root files
        run: |
          git config --global user.name "SIFR-AI Bot"
          git config --global user.email "bot@sifr-ai.com"
          git add .
          git commit -m "Autonomous deploy $(date)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.SIFR_AI_TOKEN }}@github.com/hmralawadhi/sifr-ai-homepage.git main --force
