name: Deploy to Cloudflare Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Publish to Cloudflare Pages
        run: npx wrangler pages publish dist --project-name=${{ secrets.CF_PROJECT_NAME }} --account-id=${{ secrets.CF_ACCOUNT_ID }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
